import React, { useEffect, useState, useCallback } from 'react';
import { BaseModal } from '@app/components/common/BaseModal/BaseModal';
import { BaseForm } from '@app/components/common/forms/BaseForm/BaseForm';
import { BaseInput } from '@app/components/common/inputs/BaseInput/BaseInput';
import { BaseSelect } from '@app/components/common/selects/BaseSelect/BaseSelect';
import { BaseButton } from '@app/components/common/BaseButton/BaseButton';
import { BaseSpace } from '@app/components/common/BaseSpace/BaseSpace';
import { BaseSwitch } from '@app/components/common/BaseSwitch/BaseSwitch';
import { notificationController } from '@app/controllers/notificationController';
import { UserConfig, createUserConfig, updateUserConfig, UserConfigCreate, UserConfigUpdate } from '@app/api/userconfig.api';
import { ConfigFormCards } from './ConfigFormCards';
import { JsonPreview } from './JsonPreview';
import {
  MODULE_OPTIONS_FOR_FORM,
  getConfigTypesByModule,
  generateConfigKey,
  isAutoGeneratedConfigKey,
  CONFIG_TYPE_DEFAULT_VALUES,
} from '../constants';
import * as S from './ConfigFormModal.styles';

interface ConfigFormModalProps {
  visible: boolean;
  editingConfig: UserConfig | null;
  onCancel: () => void;
  onSuccess: () => void;
}

export const ConfigFormModal: React.FC<ConfigFormModalProps> = ({
  visible,
  editingConfig,
  onCancel,
  onSuccess,
}) => {
  const [form] = BaseForm.useForm();
  const [module, setModule] = useState<string>('');
  const [configType, setConfigType] = useState<string>('');
  const [jsonConfig, setJsonConfig] = useState<Record<string, any>>({});
  const [isAutoGeneratedKey, setIsAutoGeneratedKey] = useState<boolean>(false);
  
  // 根据选中的模块动态获取配置类型选项
  // 如果未选择模块，则显示所有配置类型选项
  const configTypeOptions = module ? getConfigTypesByModule(module) : getConfigTypesByModule('');

  useEffect(() => {
    if (visible) {
      if (editingConfig) {
        form.setFieldsValue({
          module: editingConfig.module,
          config_type: editingConfig.config_type,
          config_key: editingConfig.config_key,
          description: editingConfig.description,
          is_active: editingConfig.is_active,
          is_default: editingConfig.is_default,
        });
        setModule(editingConfig.module || '');
        setConfigType(editingConfig.config_type);
        setJsonConfig(editingConfig.config_value);
        // 编辑模式下，判断配置键是否是自动生成的
        setIsAutoGeneratedKey(
          isAutoGeneratedConfigKey(
            editingConfig.config_key,
            editingConfig.module,
            editingConfig.config_type
          )
        );
      } else {
        form.resetFields();
        form.setFieldsValue({
          config_key: '',
          is_active: true,
          is_default: false,
        });
        setModule('');
        setConfigType('');
        setJsonConfig({});
        setIsAutoGeneratedKey(false);
      }
    }
  }, [visible, editingConfig, form]);


  const handleModuleChange = (value: unknown) => {
    const newModule = value as string | undefined;
    setModule(newModule || '');
    // 当模块改变时，清空配置类型选择和JSON配置
    form.setFieldsValue({ config_type: undefined, config_value: {} });
    setConfigType('');
    setJsonConfig({});
    // 清空配置键或设置为默认值（如果当前配置键是自动生成的）
    const currentKey = form.getFieldValue('config_key');
    if (isAutoGeneratedKey || !currentKey || currentKey === 'default') {
      form.setFieldsValue({ config_key: '' });
      setIsAutoGeneratedKey(false);
    }
  };

  const handleConfigTypeChange = (value: unknown) => {
    const type = value as string;
    const oldType = configType; // 保存旧类型用于判断
    
    // 如果类型没有真正改变（编辑模式下可能触发相同的 onChange），则不处理
    if (type === oldType) {
      return;
    }
    
    setConfigType(type);
    
    // 检查是否有默认值
    const defaultValue = module && type && CONFIG_TYPE_DEFAULT_VALUES[module]?.[type];
    
    if (defaultValue && !editingConfig) {
      // 新建模式且存在默认值时，使用默认值
      setJsonConfig(defaultValue);
      form.setFieldsValue({ config_value: defaultValue });
    } else if (!editingConfig) {
      // 新建模式但没有默认值时，清空配置
      form.setFieldsValue({ config_value: {} });
      setJsonConfig({});
    }
    // 编辑模式下，如果类型改变，保持当前的 jsonConfig（不在这里清空，由 useEffect 处理）
    
    // 当类型改变时，如果模块已选择，自动生成配置键
    if (module || type) {
      const autoKey = generateConfigKey(module, type);
      const currentKey = form.getFieldValue('config_key');
      
      // 仅在新建模式或配置键为空/默认值/自动生成格式时，才自动填充
      const shouldAutoFill = 
        !editingConfig || // 新建模式
        !currentKey || // 配置键为空
        currentKey === 'default' || // 配置键为默认值
        isAutoGeneratedKey || // 当前配置键是自动生成的
        (oldType && isAutoGeneratedConfigKey(currentKey, module, oldType)); // 配置键匹配旧的模块-类型组合
      
      if (shouldAutoFill) {
        form.setFieldsValue({ config_key: autoKey });
        setIsAutoGeneratedKey(true);
      }
    }
  };

  const handleFormValuesChange = useCallback(() => {
    // JSON预览会通过ConfigFormCards的onConfigValueChange自动更新
  }, []);

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      
      if (!configType) {
        notificationController.error({ message: '请选择配置类型' });
        return;
      }

      const payload: UserConfigCreate | UserConfigUpdate = {
        module: values.module,
        config_type: configType,
        config_key: values.config_key || 'default',
        config_value: jsonConfig,
        is_active: values.is_active ?? true,
        is_default: values.is_default ?? false,
        description: values.description,
      };

      if (editingConfig) {
        await updateUserConfig(editingConfig.id, payload as UserConfigUpdate);
        notificationController.success({ message: '配置已更新' });
      } else {
        await createUserConfig(payload as UserConfigCreate);
        notificationController.success({ message: '配置已创建' });
      }

      onSuccess();
    } catch (error: any) {
      notificationController.error({
        message: error?.message || '保存配置失败',
      });
    }
  };

  return (
    <BaseModal
      title={editingConfig ? '编辑配置' : '新增配置'}
      open={visible}
      onCancel={onCancel}
      width={1600}
      footer={
        <BaseSpace>
          <BaseButton onClick={onCancel}>取消</BaseButton>
          <BaseButton type="primary" onClick={handleSubmit}>
            保存
          </BaseButton>
        </BaseSpace>
      }
    >
      <S.ModalContent>
        <S.ConfigFormArea>
          <BaseForm form={form} layout="vertical" onValuesChange={handleFormValuesChange}>
            <S.FormCard>
              <S.FormCardTitle>基础信息</S.FormCardTitle>
              <BaseForm.Item
                name="module"
                label="模块"
                rules={[{ required: false, message: '请选择模块' }]}
              >
                <BaseSelect
                  options={MODULE_OPTIONS_FOR_FORM}
                  placeholder="请选择模块（可选）"
                  onChange={handleModuleChange}
                />
              </BaseForm.Item>
              <BaseForm.Item
                name="config_type"
                label="配置类型"
                rules={[{ required: true, message: '请选择配置类型' }]}
              >
                <BaseSelect
                  options={configTypeOptions}
                  placeholder="请选择配置类型"
                  onChange={handleConfigTypeChange}
                />
              </BaseForm.Item>
              <BaseForm.Item
                name="config_key"
                label="配置键"
                rules={[{ required: true, message: '请输入配置键' }]}
              >
                <BaseInput
                  placeholder={module && configType ? generateConfigKey(module, configType) : 'default'}
                  onChange={(e) => {
                    const newKey = e.target.value;
                    // 如果用户手动修改了配置键，检查是否还是自动生成的格式
                    if (module && configType) {
                      setIsAutoGeneratedKey(isAutoGeneratedConfigKey(newKey, module, configType));
                    } else if (configType) {
                      setIsAutoGeneratedKey(isAutoGeneratedConfigKey(newKey, undefined, configType));
                    } else {
                      setIsAutoGeneratedKey(false);
                    }
                  }}
                />
              </BaseForm.Item>
              <BaseForm.Item name="description" label="描述">
                <BaseInput.TextArea rows={2} placeholder="请输入配置描述" />
              </BaseForm.Item>
              <BaseForm.Item name="is_default" valuePropName="checked">
                <BaseSwitch checkedChildren="设为默认配置" unCheckedChildren="普通配置" />
              </BaseForm.Item>
              <BaseForm.Item name="is_active" valuePropName="checked">
                <BaseSwitch checkedChildren="启用" unCheckedChildren="禁用" />
              </BaseForm.Item>
            </S.FormCard>
            {configType && (
              <ConfigFormCards
                configType={configType}
                initialValue={editingConfig?.config_value || jsonConfig}
                onConfigValueChange={(value) => {
                  setJsonConfig(value);
                  handleFormValuesChange();
                }}
              />
            )}
          </BaseForm>
        </S.ConfigFormArea>
        <S.JsonPreviewArea>
          <S.JsonPreviewHeader>JSON 配置预览</S.JsonPreviewHeader>
          <JsonPreview
            config={{
              module: form.getFieldValue('module'),
              config_type: configType,
              config_key: form.getFieldValue('config_key') || 'default',
              config_value: jsonConfig,
              is_active: form.getFieldValue('is_active') ?? true,
              is_default: form.getFieldValue('is_default') ?? false,
              description: form.getFieldValue('description'),
            }}
          />
        </S.JsonPreviewArea>
      </S.ModalContent>
    </BaseModal>
  );
};

