/**
 * 用户配置常量定义
 * 用于统一管理模块和配置类型的选项
 * 
 * 模块与配置类型是 1-n 关系（一个模块包含多个配置类型）
 */

// 配置选项类型
export interface ConfigOption {
  label: string;
  value: string;
}

// 模块标签映射
const MODULE_LABEL_MAP: Record<string, string> = {
  dashboard: '看板模块',
  index: '指数模块',
  etf: 'ETF模块',
  fund: '基金模块',
  stock: '股票模块',
  system: '系统模块',
  watchlist: '自选模块',
};

// 模块与配置类型的 1-n 关系映射
// 格式：{ 模块值: [配置类型选项数组] }
export const MODULE_CONFIG_TYPE_MAP: Record<string, ConfigOption[]> = {
  dashboard: [
    { label: '看板指数概览', value: 'dashboard_index_overview' },
  ],
  index: [
    { label: '指数日线查询', value: 'index_daily_query' },
    { label: '指数周线查询', value: 'index_weekly_query' },
    { label: '大盘指数每日指标查询', value: 'index_dailybasic_query' },
    { label: '国际指数查询', value: 'index_global_query' },
    { label: '指数技术因子查询', value: 'index_factor_query' },
    { label: '申万行业日线查询', value: 'sw_daily_query' },
    { label: '指数同步设置', value: 'index_sync_settings' },
    { label: '指数显示设置', value: 'index_display_settings' },
    { label: '指数预警设置', value: 'index_alert_settings' },
  ],
  etf: [
    // 可以根据需要添加 ETF 相关的配置类型
  ],
  fund: [
    // 可以根据需要添加基金相关的配置类型
  ],
  stock: [
    // 可以根据需要添加股票相关的配置类型
  ],
  system: [
    // 可以根据需要添加系统相关的配置类型
  ],
  watchlist: [
    { label: '自选指数', value: 'base' },
    // 可以根据需要添加自选相关的配置类型
  ],
};

// 配置类型的默认值映射（基于 1-guide/config/watchlist.json）
export const CONFIG_TYPE_DEFAULT_VALUES: Record<string, Record<string, any>> = {
  watchlist: {
    base: {
      index_codes: [
        '000300.SH',
        '000852.SH',
        '399001.SZ',
      ],
      etf_codes: [
        '510300.SH',
        '159919.SZ',
        '510500.SH',
      ],
      sort_order: {
        index: {
          '000300.SH': 1,
          '000852.SH': 2,
          '399001.SZ': 3,
        },
        etf: {
          '510300.SH': 1,
          '159919.SZ': 2,
          '510500.SH': 3,
        },
      },
    },
  },
};

// 基础模块选项（从映射的key生成，不含"全部"）
export const BASE_MODULE_OPTIONS: ConfigOption[] = Object.keys(MODULE_CONFIG_TYPE_MAP).map(
  (key) => ({
    label: MODULE_LABEL_MAP[key] || key,
    value: key,
  })
);

// 基础配置类型选项（所有类型的扁平化，不含"全部"）
export const BASE_CONFIG_TYPE_OPTIONS: ConfigOption[] = Object.values(MODULE_CONFIG_TYPE_MAP).flat();

// 用于过滤的模块选项（含"全部"）
export const MODULE_OPTIONS_FOR_FILTER: ConfigOption[] = [
  { label: '全部模块', value: '' },
  ...BASE_MODULE_OPTIONS,
];

// 用于过滤的配置类型选项（含"全部"）
export const CONFIG_TYPE_OPTIONS_FOR_FILTER: ConfigOption[] = [
  { label: '全部类型', value: '' },
  ...BASE_CONFIG_TYPE_OPTIONS,
];

// 用于表单选择的模块选项（不含"全部"）
export const MODULE_OPTIONS_FOR_FORM: ConfigOption[] = BASE_MODULE_OPTIONS;

// 用于表单选择的配置类型选项（不含"全部"）
// 注意：在表单中应该使用 getConfigTypesByModule 函数根据选中的模块动态获取
export const CONFIG_TYPE_OPTIONS_FOR_FORM: ConfigOption[] = BASE_CONFIG_TYPE_OPTIONS;

/**
 * 根据模块获取对应的配置类型选项
 * @param module 模块值
 * @returns 配置类型选项数组
 */
export const getConfigTypesByModule = (module: string): ConfigOption[] => {
  if (!module) {
    return BASE_CONFIG_TYPE_OPTIONS;
  }
  return MODULE_CONFIG_TYPE_MAP[module] || [];
};

/**
 * 根据配置类型获取所属的模块
 * @param configType 配置类型值
 * @returns 模块值，如果找不到则返回 undefined
 */
export const getModuleByConfigType = (configType: string): string | undefined => {
  for (const [module, types] of Object.entries(MODULE_CONFIG_TYPE_MAP)) {
    if (types.some((type) => type.value === configType)) {
      return module;
    }
  }
  return undefined;
};

/**
 * 根据模块和配置类型生成配置键
 * @param module 模块值（可选）
 * @param configType 配置类型值
 * @returns 配置键，格式：{module}-{configType} 或 {configType}（如果 module 为空）
 */
export const generateConfigKey = (module: string | undefined, configType: string): string => {
  if (!configType) {
    return 'default';
  }
  if (module) {
    return `${module}-${configType}`;
  }
  return configType;
};

/**
 * 判断配置键是否是自动生成的格式
 * @param key 配置键
 * @param module 模块值（可选）
 * @param configType 配置类型值
 * @returns 是否是自动生成的配置键
 */
export const isAutoGeneratedConfigKey = (
  key: string,
  module: string | undefined,
  configType: string
): boolean => {
  if (!configType) {
    return false;
  }
  const expectedKey = generateConfigKey(module, configType);
  return key === expectedKey;
};

